### ISSUE TITLE
Use an existing serializer to define the format in a machine-readable way: protobuf, flatbuffers, ...

### ISSUE THREAD

**Issue by vlsi** [prusa3d/libbgcode#29]
For instance:
* https://protobuf.dev/programming-guides/proto3/
* https://github.com/nanopb/nanopb (Zlib license)
* https://flatbuffers.dev/ (Apache 2 license)
* https://embeddedproto.com/ (GPL for OSS, or commercial license available)
* CBOR. For instance, https://github.com/intel/tinycbor (MIT) However, CBOR does not declare schema

The nice features of a schema-driven format would be:
a) It would be easier to generate and parse from different languages
b) It would simplify testing both encoders and decoders. For instance, protobuf3 can be represented as JSON, so it might be useful to have "golden test inputs/outputs" stored as JSON files (human-readable), and the test frameworks could use the same JSONs converted to the binary
c) It would reduce the errors when parsing the files. As the actual "parsers and encoders" would be autogenerated, it would be impossible to set a non-existing field or something like that.
d) It would simplify schema evolution as the tools have evolution covered by default.

**Comment by bubnikv** [comment]
Thank you for your suggestion, but your proposal redefines the format significantly.
There are reasons why we defined our format the way we did and why we did not apply the frameworks you have suggested.
